version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: . # Path to Express app directory with Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: pg
      DB_PASSWORD: pg
      DB_NAME: shop
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 5000
      SECRET_KEY: gqkrqfgsg,wr..wcCdar32341gw5//qrqrqrrgbebe><,,,,FRfojwh538y7350y35-yGGWRGWqq32
      EMAIL_USER: mehrzad20061384@gmail.com
    develop:
      watch:
        - action: rebuild
          path: .
          target: /usr/src/app
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge